{
 "title": "Company Sustainability",
 "time": { "from": "2021-01-01T00:00:00.000Z", "to": "2023-12-01T00:00:00.000Z" },
 "panels": [
  {
   "title": "Total Emissions per Year",
   "type": "stat",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "masskg" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT date_trunc('year', \"month\")::timestamp as \"Year\", \ntotal_emissions as \"Yearly Emissions\" \n\nFROM total_emissions "
    }
   ]
  },
  {
   "title": "Materials Consumption",
   "type": "barchart",
   "gridPos": { "h": 20, "w": 6, "x": 7, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "masskg" } },
   "targets": [
    {
     "rawSql": "SELECT \n  material_type, \n  quantity_kg AS \"Total Consumption\" \n\nFROM materials"
    }
   ]
  },
  {
   "title": "Energy Consumption",
   "type": "barchart",
   "gridPos": { "h": 20, "w": 6, "x": 13, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "rawSql": "SELECT energy_source, \"energy_used_kWh\" AS \"Energy Consumption\" FROM energy_usage;"
    }
   ]
  },
  {
   "title": "Water Consumption per Factory",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 19, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "litre" } },
   "targets": [
    {
     "rawSql": "SELECT CAST(factory_id AS VARCHAR(20)), \"water_used_liters\" AS \"Water Consumption\" FROM water_usage;"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 5, "w": 7, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "masskg" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT date_trunc('year', \"month\")::timestamp as \"Year\", \ntotal_material_emissions as \"Material Emissions\" \n\nFROM material_emissions "
    }
   ]
  },
  {
   "title": "Waste per Factory",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 19, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "litre" } },
   "targets": [
    {
     "rawSql": "SELECT CAST(factory_id AS VARCHAR(20)), waste_type, \"amount_kg\" AS \"Waste\" FROM waste_management;"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 5, "w": 7, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "masskg" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT date_trunc('year', \"month\")::timestamp as \"Year\", \ntotal_transport_emissions as \"Transport Emissions\" \n\nFROM transport_emissions "
    }
   ]
  },
  {
   "title": "Energy Intensity - Energy per Unit / Revenue",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 5, "x": 19, "y": 14 },
   "fieldConfig": { "defaults": { "unit": " kWh/unit" } },
   "targets": [
    {
     "rawSql": "SELECT date_trunc('year', \"month\")::timestamp as \"Year\", energy_intensity_per_product as \"Energy Intensity per Product\" from energy_intensity "
    },
    {
     "rawSql": "select \n    date_trunc('year', \"month\")::timestamp as \"Year\",\n    sum(p.\"revenue\") / sum(e.\"energy_used_kWh\")  as \"Energy Intensity per Revenue\"\nfrom \"products\" p\njoin \"energy_usage\" e on date_trunc('month', p.\"month\") = date_trunc('month', e.\"timestamp\")\ngroup by \"month\";"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 5, "w": 7, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "masskg" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT date_trunc('year', \"month\")::timestamp as \"Year\", \n\"total_energy_emissions_kgCO2\" as \"Transport Emissions\" \n\nFROM energy_emissions"
    }
   ]
  },
  {
   "title": "Transport Emissions by Supplier",
   "type": "piechart",
   "gridPos": { "h": 12, "w": 3, "x": 7, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "masskg" } },
   "targets": [
    {
     "rawSql": "select \n    m.\"supplier\",\n    sum(m.\"quantity_kg\" * m.\"distance_km\" * e.\"emission_factor\") as \"Transport Emissions\"\nfrom \"materials\" m\njoin \"emission_factors\" e on m.\"transport_method\" = e.\"material\" and e.\"material_type\" = 'transport'\n\ngroup by m.\"supplier\";\n\n"
    }
   ]
  },
  {
   "title": "Material Emissions by Material",
   "type": "piechart",
   "gridPos": { "h": 12, "w": 3, "x": 10, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "masskg" } },
   "targets": [
    {
     "rawSql": "select \n    m.\"material_type\",\n    sum(m.\"quantity_kg\" * e.\"emission_factor\") as \"total_material_emissions\"\nfrom \"materials\" m\njoin \"emission_factors\" e on m.\"material_type\" = e.\"material\" and e.\"material_type\" = 'material'\ngroup by m.\"material_type\";"
    }
   ]
  },
  {
   "title": "Energy Emissions by Source",
   "type": "piechart",
   "gridPos": { "h": 12, "w": 6, "x": 13, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "masskg" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select \n    e.\"energy_source\",\n    sum(e.\"energy_used_kWh\" * ef.\"emission_factor_gCO2e_per_kWh\" / 1000) as \"total_energy_emissions_kgCO2\"\nfrom \"energy_usage\" e\njoin \"energy_emission_factors\" ef on e.\"energy_source\" = ef.\"energy_source\"\ngroup by e.\"energy_source\";"
    }
   ]
  },
  {
   "title": "Total Emissions per Factory",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 7, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "masskg" } },
   "targets": [
    {
     "rawSql": "SELECT \n    date_trunc('month', \"month\") AS \"month\",\n    f.\"name\" AS \"factory_name\",\n    SUM(te.\"total_emissions\") AS \"Emissions Factory 1\"\nFROM \n    \"total_emissions\" te\nJOIN \n    \"factories\" f ON te.\"factory_id\" = f.\"factory_id\"\nWHERE \n    te.\"factory_id\" = 1\nGROUP BY \n    date_trunc('month', \"month\"), f.\"name\"\nORDER BY \n    \"month\", f.\"name\";\n"
    },
    {
     "rawSql": "SELECT \n    date_trunc('month', \"month\") AS \"month\",\n    f.\"name\" AS \"factory_name\",\n    SUM(te.\"total_emissions\") AS \"Emissions Factory 2\"\nFROM \n    \"total_emissions\" te\nJOIN \n    \"factories\" f ON te.\"factory_id\" = f.\"factory_id\"\nWHERE \n    te.\"factory_id\" = 2\nGROUP BY \n    date_trunc('month', \"month\"), f.\"name\"\nORDER BY \n    \"month\", f.\"name\";\n"
    }
   ]
  },
  { "type": "geomap", "gridPos": { "h": 9, "w": 5, "x": 19, "y": 23 } }
 ]
}