{
 "title": "SustainabilityTables",
 "time": { "from": "2021-01-01T00:00:00.000Z", "to": "2023-12-01T00:00:00.000Z" },
 "panels": [
  {
   "title": "Total Emissions per Year",
   "type": "stat",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "masskg" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT date_trunc('year', \"month\")::timestamp as \"Year\", \ntotal_emissions as \"Yearly Emissions\" \n\nFROM total_emissions "
    }
   ]
  },
  {
   "title": "Energy Consumption by Source",
   "type": "table",
   "gridPos": { "h": 32, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "rawSql": "SELECT \nf.\"name\" as \"Factory Name\",\ndate_trunc('year', e.\"timestamp\")::timestamp as \"Year\",\ne.\"energy_source\" as \"Energy Source\",\nsum(e.\"energy_used_kWh\") as \"Energy Consumption\"\n\nfrom \"energy_usage\" e\njoin \"factories\" f on e.\"factory_id\" = f.\"factory_id\"\ngroup by e.\"timestamp\", f.\"name\", e.\"energy_source\";"
    }
   ]
  },
  {
   "title": "Material Consumption",
   "type": "table",
   "gridPos": { "h": 32, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "masskg" } },
   "targets": [
    {
     "rawSql": "SELECT \nf.\"name\" as \"Factory Name\",\ndate_trunc('year', m.\"timestamp\")::timestamp as \"Year\",\nm.\"material_type\" as \"Material\",\nsum(m.\"quantity_kg\") as \"Material Consumption\"\n\nfrom \"materials\" m\njoin \"factories\" f on m.\"factory_id\" = f.\"factory_id\"\ngroup by m.\"timestamp\", f.\"name\", m.\"material_type\";"
    }
   ]
  },
  {
   "title": "Water Consumption",
   "type": "table",
   "gridPos": { "h": 11, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "litre" } },
   "targets": [
    {
     "rawSql": "SELECT \ndate_trunc('year', w.\"timestamp\")::timestamp as \"Year\",\nf.\"name\" as \"Factory Name\",\nsum(w.\"water_used_liters\") as \"Water Consumption\"\n\nfrom \"water_usage\" w\njoin \"factories\" f on w.\"factory_id\" = f.\"factory_id\"\ngroup by w.\"timestamp\", f.\"name\";"
    }
   ]
  },
  {
   "title": "Total Emissions by Factory",
   "type": "table",
   "gridPos": { "h": 11, "w": 6, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "masskg" } },
   "targets": [
    {
     "rawSql": "SELECT \ndate_trunc('year', \"month\")::timestamp as \"Year\", \nfactory_name as \"Factory Name\",\ntotal_emissions as \"Yearly Emissions [kg CO2eq.]\" \n\nFROM total_emissions"
    }
   ]
  },
  {
   "title": "Waste Management",
   "type": "table",
   "gridPos": { "h": 11, "w": 6, "x": 18, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "litre" } },
   "targets": [
    {
     "rawSql": "SELECT \ndate_trunc('year', w.\"timestamp\")::timestamp as \"Year\",\nf.\"name\" as \"Factory Name\",\nw.waste_type as \"Waste Type\",\nsum(w.\"amount_kg\") as \"Waste\"\n\nfrom \"waste_management\" w\njoin \"factories\" f on w.\"factory_id\" = f.\"factory_id\"\ngroup by w.\"timestamp\", f.\"name\",w.waste_type;"
    }
   ]
  },
  {
   "title": "Emissions by Factory with Filter (Material, Transport, Energy)",
   "type": "table",
   "gridPos": { "h": 12, "w": 6, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "masskg" } },
   "targets": [
    {
     "rawSql": "SELECT \ndate_trunc('year', \"month\")::timestamp as \"Year\", \nfactory_name as \"Factory Name\",\ntotal_material_emissions as \"Material Emissions [kg CO2eq.]\" \n\nFROM material_emissions"
    },
    {
     "rawSql": "SELECT \ndate_trunc('year', \"month\")::timestamp as \"Year\", \nfactory_name as \"Factory Name\",\ntotal_transport_emissions as \"Transport Emissions [kg CO2eq.]\" \n\nFROM transport_emissions"
    },
    {
     "rawSql": "SELECT \ndate_trunc('year', \"month\")::timestamp as \"Year\", \nfactory_name as \"Factory Name\",\n\"total_energy_emissions_kgCO2\" as \"Energy Emissions [kg CO2eq.]\" \n\nFROM energy_emissions"
    }
   ]
  },
  {
   "title": "Total Products per Year",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT date_trunc('year', \"month\")::timestamp as \"Year\", \nquantity_sold as \"Produced Products\" \n\nFROM products "
    }
   ]
  },
  {
   "title": "Total Revenue per Year",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT date_trunc('year', \"month\")::timestamp as \"Year\", \nrevenue as \"Revenue\" \n\nFROM products "
    }
   ]
  }
 ]
}